#!/usr/bin/python3

"""This defines a base model class."""
import json
import csv
import turtle

# models/base.py
class Base:
    # Private class attribute to keep track of the number of objects created.
    __nb_objects = 0

    def __init__(self, id=None):
        """
        Constructor for the Base class.

        :parameter id: An integer representing the object's id (optional).
        If provided, the id attribute is set to the given value.
        If id is not provided, the id is auto-generated by 
        incrementing __nb_objects.
        """
        if id is not None:
            self.id = id
        else:
            """
            If id is not provided, 
            auto-generate the id by incrementing __nb_objects.
            """
            Base.__nb_objects += 1
            self.id = Base.__nb_objects
